name: graphai-for-tcm
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.7.1
  - pytorch-geometric=2.6.1
  - numpy=2.3.0
  - pandas=2.3.0
  - scipy=1.15.3
  - scikit-learn=1.7.0
  - matplotlib=3.10.3
  - tqdm=4.67.1
  - networkx>=3.3,<4
  - openpyxl>=3.1,<4
  - notebook>=7,<8
  - ipykernel>=6,<7
  - pip
  - pip:
      - hypernetx>=2.4,<3
